new workflow

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -22,17 +22,18 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-  build:
+  build-and-run:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-      # This is used to complete the identity challenge
-      # with sigstore/fulcio when running outside of PRs.
-      id-token: write
 
     steps:
-      - name: build
+      - name: Checkout repository
         uses: actions/checkout@v2
+
+      # Build the Docker image
       - name: Build Docker image
-        run: docker build -t myimage:latest .
+        run: docker build -t myimage .
+
+      # Run the Docker container and fail if the container's run command exits with non-zero exit code
+      - name: Run Docker container
+        run: |
+          docker run --rm myimage || exit 1
